services:
  - type: web
    name: vernika-hra
    env: python
    buildCommand: pip install -r requirements-web.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT web_main:main
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        sync: false

